### ISSUE TITLE
Proposition

### ISSUE THREAD

**Issue by cedricbonhomme** [amq/firefox-debloat#6]
Thank you for tips. Here is my Firefox configuration:
https://bitbucket.org/snippets/cedricbonhomme/cbj6
if it can help you.

**Comment by amq** [comment]
Thanks.

I wouldn't aggree with the following though:
```
user_pref("javascript.enabled", false);
```
Most of the sites strongly rely on Javascript. It would be better to use something like [NoScript](https://addons.mozilla.org/En-us/firefox/addon/noscript/).

```
user_pref("network.http.sendRefererHeader", 0);
```
This will also break many sites. I'd recommend [Smart Referrer](https://addons.mozilla.org/en-us/firefox/addon/smart-referer) instead.

**Comment by cedricbonhomme** [comment]
Thanks for Smart Referrer, I didn't knew it.
Indeed, I have some problems with the login on Bitbucket. But I rarely identify myself to sites.

I admit that disabling JavaScript is restrictive. I only activate JavaScript when it is really needed. For example GitHub is quite usable with the Tor browser and the highest security level. Not the case for Lotus Notes.

**Comment by rastus-vernon** [comment]
No need for Smart Referrer. There are other settings that make the referrer header not leak any important information, or only be sent in some cases. `network.http.referer.spoofSource`, `network.http.referer.trimmingPolicy` and `network.http.referer.sendAcrossOrigins` are examples.

**Comment by jomo** [comment]
Indeed, what @rastus-vernon said.

- `network.http.referer.XOriginPolicy`:  
 **0**: always send  
 **1**: send if base domains match  
 **2**: send if hosts match  
- `network.http.referer.spoofSource`:  
 **false**: real referer  
 **true**: spoof referer (use target URI as referer)
- `network.http.referer.trimmingPolicy`:  
 **0**: send full URI  
 **1**: scheme+host+port+path  
 **2**: scheme+host+port

----

I recommend setting XOriginPolicy to 1, spoofSource to false, trimmingPolicy to 1.
Otherwise quite a few sites will malfunction and you'll have no idea why.
The information you send to websites with these settings can be collected on the server side anyway.

Even with these settings, it's somtimes (very rare though) required to temporarily set XOriginPolicy to 0 for some sites.

**Comment by rastus-vernon** [comment]
@jomo Won't websites always work with spoofSource set to true? If they do, then nothing else is required since that makes the page itself be sent as the referer, and the website already knows what page you're visiting. In any case, it seems to me it should work since you can generally visit a website directly with the URL.

**Comment by jomo** [comment]
Some websites only work when they see the user is coming from a specific page (or subdomain). I don't have any examples right now, but it has definitely happened to me.
spoofSource would also send a (fake) Referrer even if it wouldn't send it by default.

spoofing or not, it's not like you're 'leaking' any secret information, it's not much of a privacy concern.
